import {
  exportNodeAsImage,
  getAnnotations,
  getDocumentInfo,
  getInstanceOverrides,
  getLocalComponents,
  getNodeInfo,
  getNodesInfo,
  getReactions,
  getSelection,
  getStyles,
  readMyDesign,
  scanNodesByTypes,
  scanTextNodes,
} from './figma-tools';

export const reviewTools = {
  get_node_info: getNodeInfo,
  get_nodes_info: getNodesInfo,
  get_selection: getSelection,
  get_document_info: getDocumentInfo,
  get_styles: getStyles,
  get_annotations: getAnnotations,
  scan_nodes_by_types: scanNodesByTypes,
  scan_text_nodes: scanTextNodes,
  read_my_design: readMyDesign,
  export_node_as_image: exportNodeAsImage,
  get_instance_overrides: getInstanceOverrides,
  get_local_components: getLocalComponents,
  get_reactions: getReactions,
};
